easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
  entities:
    #        # List the entity class name you want to manage
    #        - App\Entity\Product
    #        - App\Entity\Category
    #        - App\Entity\User
    Carousel:
      class: App\Entity\Carousel
      form:
        fields:
          - { property: 'titre', type: 'fos_ckeditor' }
          - { property: 'description', type: 'fos_ckeditor' }
          - { property: 'image', type: 'image', base_path: '%app.path.carousel_images%' }
    Article:
      class: App\Entity\Article
      form:
        fields:
          - { property: 'titre', type: 'fos_ckeditor' }
          - { property: 'contenu', type: 'fos_ckeditor' }
    Contact:
      class: App\Entity\Contact
      list:
        fields:
          - nom
          - entreprise
          - email
          - { property: 'pays', type: 'country' }
          - sujet
          - message
      show:
        fields:
          - nom
          - entreprise
          - email
          - { property: 'pays', type: 'country' }
          - sujet
          - message
      form:
        fields:
          - nom
          - entreprise
          - email
          - { property: 'pays', type: 'country' }
          - sujet
          - message
    Annuaire:
      class: App\Entity\Annuaire
    Email:
      class: App\Entity\Email
    Config:
      class: App\Entity\Config
      list:
        fields:
          - nomSocieter
          - adresse
          - emails
          - tels
          - { property: 'logo', type: 'image', base_path: '%app.path.logo_images%' }
      show:
        fields:
          - nomSocieter
          - adresse
          - emails
          - tels
          - { property: 'logo', type: 'image', base_path: '%app.path.logo_images%' }
      form:
        fields:
          - nomSocieter
          - adresse
          - { property: 'tels', type: 'collection' , type_options: { entry_type: App\Form\AnnuaireType,allow_delete: true,allow_add: true ,by_reference: false }}
          - { property: 'emails', type: 'collection'  , type_options: { entry_type: App\Form\EmailType,allow_delete: true,allow_add: true ,by_reference: false }}
          - { property: 'logoFile', type: 'vich_image' }